### ISSUE TITLE
Provide import facility to populate the setting from the legacy server manager

### ISSUE THREAD

**Issue by isc-jamien** [intersystems-community/intersystems-servermanager#1]
On the Windows platform the InterSystems cube provides access to a facility for defining server connections. This information is stored in the Windows Registry. The ability to import the server connections defined therein  would be very helpful for those transitioning from Studio.

**Comment by gjsjohnmurray** [comment]
@isc-jamien is any work underway on this yet? If so, can the GH issue be assigned to someone so as to indicate this?

**Comment by timleavitt** [comment]
Please assign it to me. Tyler (who isn't available a bit) has published his work in progress at https://github.com/ty-d/intersystems-servermanager/tree/ImportServersFromRegistry and I intend to finish it up and submit a PR this month.

**Comment by gjsjohnmurray** [comment]
Registry pointer in [Developer Community post](https://community.intersystems.com/post/cache-client-install-automation-where-are-remote-server-settings-stored-windows-10-pc).

**Comment by timleavitt** [comment]
@gjsjohnmurray thanks - this is in-progress but has gotten bumped by some other things priority-wise.
