### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Hkchill** [intersystems-community/intersystems-servermanager#101]
- Issue Type: `Performance`
- Extension Name: `servermanager`
- Extension Version: `2.0.5`
- OS Version: `Windows_NT x64 10.0.16299`
- VS Code version: `1.58.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\GOLFRI~1\AppData\Local\Temp\intersystems-community.servermanager-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by gjsjohnmurray** [comment]
Unactionable because CPU profile was not attached.
