### ISSUE TITLE
unable to Edit/View Code after opening a server with pathPrefix

### ISSUE THREAD

**Issue by theflyingape** [intersystems-community/intersystems-servermanager#102]
Issue #95 was corrected to open a server's Namespace and Management Portal in a Tab configured with `pathPrefix`, but subsequently, adding a Namespace for Edit or View Code ~~asserts~~ asserted this failure:
![image](https://user-images.githubusercontent.com/19166945/126493592-3568480f-40c5-4c47-835f-93b2ebcf8fb0.png)

I took notice now on my FIRST connection that it _sometimes_ puts 2 different icons (new to me): open CSP files for editing or viewing and not the open Code for editing or viewing icons.  On this particular host with multiple instances, I do not have any exclusive CSP file URLs since it's designated for DR mirrored datasets only and as such are read-only all of the time.

This is difficult to reproduce now.  I will certainly reference this issue again if I can find clear path to reproduce that 2nd set of option icons.  Thanks for the fixes!

**Comment by gjsjohnmurray** [comment]
@theflyingape have you seen this happen again? If not I suggest we close the issue.

**Comment by theflyingape** [comment]
Agreed, thanks, closing.
