### ISSUE TITLE
Don't allow users to leave username blank when adding new server via UI

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/intersystems-servermanager#124]
One of our devs just got started with VS Code and they ran into issues with the Language Server failing when trying to get server information from the main extension. We discovered that the issue is due to there being no username and password returned from the main extension because the dev left their username blank when setting up the server. I don't think users should be allowed to omit a username when configuring a server.

**Comment by gjsjohnmurray** [comment]
Doing this would mean we no longer support situations where the user deliberately wants the opportunity to enter a username at connection time.

I guess the problem the LS has is that even though the main extension prompted the dev for username this doesn't get returned in the `serverForUri` API result object which LS gets from it.

I think we could improve `serverForUri` to add the connect-time-entered username in this case. Would that meet your need?

**Comment by isc-bsaviano** [comment]
That would be ok. I would need the password as well, at least until the auth provider is released and you could store the password there.

**Comment by isc-bsaviano** [comment]
Fixed by #141
