### ISSUE TITLE
Authorization error on new M1 mac

### ISSUE THREAD

**Issue by JeffSemmens** [intersystems-community/intersystems-servermanager#152]
Issue Type: <b>Bug</b>

I am using VS code to connect with containers.intersystems.com/intersystems/irishealth-community-arm64:2022.1.0.209.0. I have created a server definition with the following server definition:

        "sdashredder": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52773
            },
            "description": "SDA Shredder Demo",
            "username": "iscusr"
        }

When I try to connect the plugin I am prompted for my password (which I given) and it still gives me the following error:

Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on 127.0.0.1:52773[SDASHREDDER]

If I go to a browser and bring up the systems management portal, I am able to login with the username set up in my server definition and with same password I try to use in vscode.

Extension version: 3.1.2022062901
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:32:39.000Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id f83cae59-87d1-4f98-b9b2-5a03fa3d1ba6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728

```

</details>

**Comment by JeffSemmens** [comment]
Turns out I needed to follow the documentation and change the cookies to "auto-detect". Once I did that it now works. Not sure if this has changed but I hadn't had to do that before. All good now.

**Comment by gjsjohnmurray** [comment]
> Turns out I needed to follow the documentation and change the cookies to "auto-detect".

@JeffSemmens are you referring to the README section titled [Notes About Simple Browser](https://github.com/intersystems-community/intersystems-servermanager#notes-about-simple-browser)?

If so, I'm not sure why it was necessary for you to make those changes to the /csp/sys/* web app settings except to get the IRIS login page working when launched from the "Open Management Portal in Tab" button.

What version of the InterSystems ObjectScript extension have you installed? Since you're using the prerelease version of Server Manager (3.1.2022062901) you may want to use the prerelease version of InterSystems ObjectScript as well, so you get the full benefit of Server Manager 3's Authentication Provider.

**Comment by JeffSemmens** [comment]
At this point I’m not sure what was going on as I changed all of the settings back (Since I don’t tend to use the Simple browser and I didn’t want to have to make those changes every time I spun up a new container from my image. It looks like I pulled down the pre-release of the server manager but only 1.8.1 of the objectscript extension. I’ll look at moving to the pre-release of that as well.

Jeff

Jeff Semmens
Senior Sales Engineer | InterSystems
Direct: +1.951.677.9475 | Mobile: +1.951.768.8813


[wO2Tj3GzmVRiAAAAABJRU5ErkJggg==]



From: John Murray ***@***.***>
Reply-To: intersystems-community/intersystems-servermanager ***@***.***>
Date: Thursday, August 4, 2022 at 1:51 AM
To: intersystems-community/intersystems-servermanager ***@***.***>
Cc: Jeff Semmens ***@***.***>, Mention ***@***.***>
Subject: Re: [intersystems-community/intersystems-servermanager] Authorization error on new M1 mac (Issue #152)


Turns out I needed to follow the documentation and change the cookies to "auto-detect".

@JeffSemmens<https://github.com/JeffSemmens> are you referring to the README section titled Notes About Simple Browser<https://github.com/intersystems-community/intersystems-servermanager#notes-about-simple-browser>?

If so, I'm not sure why it was necessary for you to make those changes to the /csp/sys/* web app settings except to get the IRIS login page working when launched from the "Open Management Portal in Tab" button.

What version of the InterSystems ObjectScript extension have you installed? Since you're using the prerelease version of Server Manager (3.1.2022062901) you may want to use the prerelease version of InterSystems ObjectScript as well, so you get the full benefit of Server Manager 3's Authentication Provider.
