### ISSUE TITLE
"Open Management Portal in Tab" gets stuck on Login Screen

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/intersystems-servermanager#171]
Type: <b>Bug</b>

1. Define a connection using Server Manager. I am connecting VS Code to two different IRIS instances in containers; the reported behavior happens with either container.
2. Use InterSystems Tools and select the connection.
3. Supply username/password.
4. Use "tools" icon to select "Open Management Portal in Tab".
At this point, one of two things happens:
* Home Page of Portal correctly displays, but clicking on any section (System Operation for example) brings up the login screen, and supplying un/pw doesn't help; you're stuck on the login screen.
* Login screen displays, and supplying un/pw doesn't help; you're stuck on the login screen.

Note that the URL displayed in the Simple Browser contains the CSPCHD parameter. Also note that using the icon for "Open Management Portal in External Browser" works correctly.

Extension version: 3.2.1
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
Did you make the server-side changes described in the second bullet at https://github.com/intersystems-community/intersystems-servermanager#notes-about-simple-browser?

**Comment by isc-solon** [comment]
Well, um, no. I read through those notes (too quickly), and when I saw that **the URL already contained** the CSPCHD parameter, I concluded that I was all set, and that I was seeing a new bug. I changed the settings to AutoDetect and it all works as it should. You can close this as "this guy should read carefully."

**Comment by gjsjohnmurray** [comment]
Good to know you were able to resolve your issue. I'll close this, but also plant the idea that you might try to convince ISC devs / PMs that these changes could be made in a future IRIS release so it's no longer necessary for Server Manager users to do them manually.
