### ISSUE TITLE
VS Code Failing to Connect to Environments After Updates

### ISSUE THREAD

**Issue by semerson-glytec** [intersystems-community/intersystems-servermanager#176]
Type: <b>Bug</b>

Version is IRIS for UNIX (Ubuntu Server 20.04 LTS for x86-64) 2022.1.2 (Build 574U) Fri Jan 13 2023 15:03:40 EST [Health:3.5.0-1.m1]

Over the weekend it appears that automatic updates were installed in VS Code, and now my existing environment connections are failing. This is also happening to my other teammates that have the VS Code updates, but not one that has not taken them yet. As such, we believe the issue is some incompatibility with the InterSystems packages and something that had changed during the VS Code update.

My current VS Code version information from the "About" option is:

Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

And my team member whose connections are still functioning has:

Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

This issue has happened to me a couple of times before, but it has always gone away without explanation, or was resolved after copying the connection settings from the settings.json file from a coworker. However, this time around the majority of my team is affected, and we noticed the key different between affected and unaffected is having the upgrades installed. 

As for the extension versions, my coworker and I both have:

InterSystems Language Server v2.3.
InterSystems ObjectScript v2.8.0
InterSystems Server Manager v3.2.2

When attempting to interact with previously opened Namespace connections the following error is returned

Extension version: 3.2.2
![image_720](https://user-images.githubusercontent.com/132935287/236888071-b35ce2fe-fdf4-4cbb-b5ef-a55a699c2cb3.png)

but when trying to create a new connection all that's visible is this, instead of the regular list of Namespaces

![image](https://user-images.githubusercontent.com/132935287/236888344-f925732c-c88d-4f8b-901a-3690591b77fe.png)

Finally, another coworker that is currently experiencing this issue report occasional successful connections of http rather than https, but nothing that has been reliable for working with.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.12GB free)|
|Process Argv|--crash-reporter-id a6b55c02-5ca4-4e3c-99fa-dabd1750e11b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by gjsjohnmurray** [comment]
Please confirm that your settings include `"http.proxyStrictSSL": false`

**Comment by AndrewBartholomewVA** [comment]
Same problem here at the VA. We did find a work around by installing another extension called win-ca, which projects your trusted certificates to VSC extensions

**Comment by AndrewBartholomewVA** [comment]
Don't know if it's related but there was a change to the objectscript extension two weeks ago that mentions certificates.

https://github.com/intersystems-community/vscode-objectscript/commit/789d373e24686044c89dc8c79496b1c2332e6d3f

**Comment by gjsjohnmurray** [comment]
This is almost certainly caused by https://github.com/microsoft/vscode/issues/181404 which is expected to be fixed in upcoming 1.78.1. Meanwhile you may want to downgrade to 1.77.3.

**Comment by semerson-glytec** [comment]
Alright, I've downgraded to 1.77.3 and that resolved the issue, so I've spread the word to my team. I've also disabled automatic updates so an unexpected upgrade doesn't cause this exact same issue again.

Would it be best to follow https://github.com/microsoft/vscode/issues/181404 to track the release of 1.78.1 for the expected resolution to this problem, or will there be an update to this ticket as well?

**Comment by gjsjohnmurray** [comment]
1.78.1 became a security release, so it's 1.78.2 you need to look for. See https://github.com/microsoft/vscode/issues/181866 for the endgame. I will update this issue after it has shipped.

**Comment by semerson-glytec** [comment]
Thank you for the update! I'll keep my eyes open

**Comment by semerson-glytec** [comment]
Thank you for the heads up John! I just took the update, and I can connect to our environments and namespaces as expected. I sent the word along to my team, so we should be all set.

**Comment by AndrewBartholomewVA** [comment]
This is working for us as well. Thanks for the update.
