### ISSUE TITLE
Remove default servers

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/intersystems-servermanager#203]
I think we should remove these. They add clutter to menus and the settings.json, and with the PWS removal in IRIS 2023.2 the IRIS default one will be incorrect.

**Comment by gjsjohnmurray** [comment]
I tend to agree, though PWS will remain in Community Edition. But we should probably do the removal in such a way that anyone relying on the implicit existence of default definitions "default\~iris", "default\~cache" or "default\~ensemble" won't suddenly have their workspaces broken.
