### ISSUE TITLE
Adding a new "default~iris~nopws' setting?

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/intersystems-servermanager#211]
Are you considering adding something like the following to Server Manager settings?
"default~iris~nopws": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 80,
                "pathPrefix": "/iris"
            },
            "description": "Connection to local InterSystems IRIS™ without PWS installed with default settings."
        },

I realize that the port and pathPrefix could be different. I'm really posting this to see what your thoughts are.

**Comment by gjsjohnmurray** [comment]
In response to #203 we removed the default server entries in 3.4.2
