### ISSUE TITLE
On Windows, removing a server definition from settings.json doesn't remove it from the list of Recent servers

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/intersystems-servermanager#212]
If I remove a server definition from settings.json:

- On Mac connected to IRIS Ubuntu, it immediately disappears from the Recent servers list.
- On Windows connected locally, the deleted server remains in the list.

Is there a place on Windows I can go and manually remove the deleted server from the list?

**Comment by gjsjohnmurray** [comment]
Is the zombie server name in the Recent tree perhaps one of the `default~xxx` ones?

**Comment by isc-solon** [comment]
it is default~iris, leftover from an earlier version.

**Comment by gjsjohnmurray** [comment]
Can you tolerate the zombie until it falls off the Recents list when you have connected to 8 other servers more recently? The list is persisted in a storage area VS Code provides to extension authors. On VS Code Desktop this uses a SQLite database file, so it's not amenable to manual manipulation.

**Comment by isc-solon** [comment]
I can tolerate a great many things, including this. So the different behavior on Mac vs Windows is expected?
The reason for wanting to remove it is to provide a no-leftovers clean training environment. We don't want students to accidentally pick that server, since we have a new "iris" server set up for them. Should there be a "clear recent servers" feature?

**Comment by gjsjohnmurray** [comment]
Please download [this dev build zip](https://github.com/intersystems-community/intersystems-servermanager/suites/15207835037/artifacts/869094632), extract the VSIX, install it and try this:

![image](https://github.com/intersystems-community/intersystems-servermanager/assets/6726799/549b918f-a881-422b-a159-0ecb4822f61a)
