### ISSUE TITLE
Remove use of `keytar`

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/intersystems-servermanager#215]
VS Code removed its built-in `keytar` in [version 1.83](https://code.visualstudio.com/updates/v1_83#_keytar-removed-from-vs-code). We should remove all usage of that module in this extension.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano #190 was supposed to cover this. Are you seeing a problem?

**Comment by isc-bsaviano** [comment]
My bad, my fork was way out of date! Sorry
