### ISSUE TITLE
Easy Access to setting.json

### ISSUE THREAD

**Issue by mmassias** [intersystems-community/intersystems-servermanager#227]
Type: <b>Bug</b>

Hi,
It would be great to be able to access settings.json directly from the "servers" view without having to search for setting-intersystems and so on.

Thanks,
Mark

Extension version: 3.6.1
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13800H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.62GB (10.70GB free)|
|Process Argv|--crash-reporter-id 6e1da3bb-9b02-4f5b-9446-28dcb121dc70|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by isc-bsaviano** [comment]
Hi @mmassias, can you please clarify the request please? If you right-click on a server in the tree there is a menu option called `Edit Settings`.

**Comment by gjsjohnmurray** [comment]
I assume you have already discovered the `Edit Settings` option from each server's context menu. It is also available from the titlebar's `...` menu.

Those lead you to VS Code's Settings Editor, filtered to show only the settings for this extension. However the bulk of its settings lie in the `intersystems.servers` object, which Settings Editor can't handle. So instead you get a link to that object in your `settings.json` etc.

What is your suggestion?

**Comment by mmassias** [comment]
Hi Brett, what I am suggesting is a direct entry point to settings.json, i.e. less number of clicks to get there. Thanks, Mark
