### ISSUE TITLE
since moving to 1.0.0 new servers fail to save

### ISSUE THREAD

**Issue by bourette** [intersystems-community/intersystems-servermanager#45]
I updated to 1.0.0 and attempting to add new servers fails.  I dropped back to 0.9.3 and it succeeds.

**Comment by gjsjohnmurray** [comment]
I haven't been able to reproduce this. I used the "+" button on the server picker and completed the definition journey. Next time I went into server picker my new server was near the bottom of the list. I also verified the definition is present in user settings JSON.

**Comment by gjsjohnmurray** [comment]
@bourette you wrote you dropped back to 0.9.3. Did you mean 0.9.2, seeing as there was no 0.9.3 of Server Manager?

**Comment by bourette** [comment]
Sorry, 0.9.3-beta.1

On Oct 19, 2020, at 4:18 PM, John Murray <notifications@github.com<mailto:notifications@github.com>> wrote:



@bourette<https://github.com/bourette> you wrote you dropped back to 0.9.3. Did you mean 0.9.2, seeing as there was no 0.9.3 of Server Manager?

**Comment by gjsjohnmurray** [comment]
> Sorry, 0.9.3-beta.1

The [diff](https://github.com/intersystems-community/intersystems-servermanager/compare/v0.9.3-beta.1...v1.0.0) shows only 2 files changed. One is the README, and the other is where we bumped the version number to 1.0.0 and removed the Preview flag. So I'm puzzled you're seeing a bug in 1.0.0 that you don't see in 0.9.3-beta.1

**Comment by bourette** [comment]
A restart and reload of 1.0.0 seems to have resolved this.
