### ISSUE TITLE
Icon lacks transparency outside the circle

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/intersystems-servermanager#46]
![image](https://user-images.githubusercontent.com/6726799/96587334-1e923180-12da-11eb-9b00-f51b5d4b7975.png)

**Comment by daimor** [comment]
![image](https://user-images.githubusercontent.com/1212251/96587631-3de58a80-12eb-11eb-9346-1968682e7a7c.png)

**Comment by gjsjohnmurray** [comment]
@isc-rsingh I think you sourced this PNG internally. Please get the creator to do one with a transparent surround. Then either submit it in a PR or email it to me and I'll handle that part.
