### ISSUE TITLE
Can the three built-in default servers be removed?

### ISSUE THREAD

**Issue by isc-acoppola** [intersystems-community/intersystems-servermanager#64]
Can "default\~iris", "default\~cache", and "default\~ensemble" be removed, using Clear Password from Keychain, or any other method? Removing them at the user level doesn't seem to change anything.
If they can't be removed, is it possible to suppress their display?

**Comment by gjsjohnmurray** [comment]
@isc-acoppola I have pushed a PR that implements a new setting. By adding `"/hideEmbeddedEntries": true` to your settings JSON you can prevent those three built-in server definitions from showing in the pick lists. For example,

```
"intersystems.servers": {
		"/hideEmbeddedEntries": true,
		"myserver": {
...
```

Please try it out by downloading [this VSIX file](https://github.com/intersystems-community/intersystems-servermanager/suites/1914534060/artifacts/37648936) and installing it (drag/drop onto your Extensions view is one way to do that).

Make sure your JSON doesn't explicitly define those servers, else they will still appear.

**Comment by isc-acoppola** [comment]
John,
I loaded your VSIX, and it appears to work as intended. 
Thank you!
