### ISSUE TITLE
Authorization failure after upgrade 

### ISSUE THREAD

**Issue by bourette** [intersystems-community/intersystems-servermanager#86]
Issue Type: <b>Bug</b>

After upgrade I get continual authorization errors.
Server 2.0.3 ObjectScript 1.0.11

Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[HSLIB]
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[%SYS]
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[HSLIB]
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[%SYS]
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[HSLIB]
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on localhost:52777[%SYS]

Extension version: 2.0.3
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 87c1cdb2-fea9-4db7-a129-27164053787c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30294772
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30294816
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353

```

</details>

**Comment by gjsjohnmurray** [comment]
Is this happening with a workspace that has isfs root(s)?

Are you using the ?ns=XXX notation in the isfs uri9s), or the server:ns syntax?

Please use the "Install Another Version..." option from the gearwheel menu of Server Manager in the Extensions view, downgrade to 2.0.2 and see if the problem goes away. If it doesn't, update to 2.0.3 again and try downgrading the ObjectScript extension to 1.0.10. This may help us pinpoint what's happening.

**Comment by bourette** [comment]
I couldn't wait 24 hours ;) so I just set my password again from preferences.
