### ISSUE TITLE
Allow extension in untrusted workspaces

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/intersystems-servermanager#92]
Once VS Code 1.57 ships extensions will default to being disabled in every workspace until the user declares that they trust the workspace. See https://github.com/microsoft/vscode/issues/120251 and https://code.visualstudio.com/docs/editor/workspace-trust

This extension doesn't expose the user to any risks which the contents of a workspace could pose, so we should mark it appropriately in its `package.json`

```
	"capabilities": {
		"untrustedWorkspaces": {
			"supported": true
		}
	},
```

I will submit a PR.

**Comment by gjsjohnmurray** [comment]
@daimor please do the same for vscode-objectscript

@isc-bsaviano please do likewise for language-server

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Done. LS 1.2.0 is live
